@ROOT_URL = http://localhost:3000
@sid=s%3AHWHIYa2xPMO5SC6wEdFHMgMbpZV4w_Ny.otuLokfFchzhcIljRPTgQTU8%2B5fGKjb%2B0DNMZit%2By5Q
GET {{ROOT_URL}}/home
###
GET {{ROOT_URL}}/isAuth
###
// Register Success
POST {{ROOT_URL}}/auth/signin HTTP/1.1
content-type: application/json

{
    "name": "Roman Munar",
    "email": "roman.munar1@gmail.com",
    "password": "superS3cret",
    "passwordConfirmation": "superS3cret"
}

###
// Login Success
POST {{ROOT_URL}}/auth/signin HTTP/1.1
content-type: application/json

{
    "email": "roman.muaanaar1@gmail.com",
    "password": "superS3cret"
}

###
// Logout Success
POST {{ROOT_URL}}/auth/logout HTTP/1.1
content-type: application/json
sid: {{sid}}

{
    "email": "roman.muaanar1@gmail.com",
    "password": "superS3cret"
}


###
// Fails email validation
POST {{ROOT_URL}}/auth/signin HTTP/1.1
content-type: application/json
sid: {{sid}}

{
    "email": "roman.munar1gmail.com",
    "password": "superS3cret"
}

###
// Fails password validation
POST {{ROOT_URL}}/auth/signin HTTP/1.1
content-type: application/json
sid: {{sid}}

{
    "email": "roman.munar1@gmail.com",
    "password": "supersecret"
}